language: python
python:
  - "3.7.3"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest -vvs -p no:warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)