language: python
python:
  - "3.5"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - run_unit_test_suite
after_success:
  - bash <(curl -s https://codecov.io/bash)