language: python
python:
  - "3.5"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest -k "unit" -x --cov-config .coveragerc --cov=chamber chamber/tests -p no:warnings --ignore=tests_depreciated\
after_success:
  - bash <(curl -s https://codecov.io/bash)